import type { Load } from "@sveltejs/kit";

export const load: Load = () => {
    return {
        weapons: [
            [
                "CQ",
                "Calamity Queller",
                "Great for support, good for off-field DPS, mediocre for on-field DPS",
                "This is her signature weapon and offers a massive ATK boost that increases over time. While it does offer the highest Icy Quill damage ceiling, owing to the highest base ATK among all weapons, it can take a lot of effort to build around due to lacking ER and energy-related utility. It will most likely require getting ER sands or god-tier artifact substats to ensure consistent Elemental Burst usage.",
                "For off-field DPS Shenhe, this is still decent especially if you have other characters that can use Icy Quills, but is outperformed by other options.",
                "For on-field DPS Shenhe, this still works, but you get stacks more much slowly and won't have the doubled bonus from being off-field, so this isn't a recommended choice over other options.",
            ],
            [
                "FL",
                "Favonius Lance",
                "Great for support",
                "This is the default option, offering good ER% and an excellent passive for batterying your core unit. This is an amazing weapon for Shenhe and scales well with all levels of investment while offering good QoL for team energy generation.",
                "Note that it does require you to have some CRIT Rate investment to use the passive well, but you can ideally gain enough CRIT Rate from artifact substats and still run ATK% main stat artifacts.",
            ],
            [
                "MW",
                "Missive Windspear",
                "Good for support, decent for on/off-field DPS",
                "This is surprisingly competitive for a F2P weapon, but is reliant on Shenhe triggering an Elemental Reaction to get the ATK% buff; otherwise, it falls behind. The EM buff is not useful beyond some niche teams.",
                "For DPS Shenhe, this is more of less just a stat-stick and requires Shenhe to trigger an Elemental Reaction to keep up its passive. Again, the EM buff is probably not that useful for her. This is a fine option if better options are not available.",
            ],
            [
                "EL",
                "Engulfing Lightning",
                "Great for off-field DPS, good for support",
                "This is a good compromise between Shenhe's ER needs and prioritizing Icy Quill damage, turning Shenhe's ER needs into a benefit. It is highly recommended to start rotations with her Elemental Burst.",
                "With off-field DPS Shenhe, she is reliant on her Elemental Burst's damage, so EL will help facilitate her high ER needs while providing good damage.",
            ],
            [
                "SS",
                "Skyward Spine",
                "Good for support",
                "A standard banner weapon with good ER and high ATK, second only to Calamity Queller itself. This is commonly used as a way to push for higher ATK than Favonius Lance can offer and works well if your core unit's ER needs can be met.",
            ],
            [
                "WF",
                "Wavebreaker's Fin",
                "Great for on/off-field DPS at high refinement, good for support",
                "An ATK stat-stick that can allow Shenhe's Elemental Burst to hit hard at high refinements. Make sure you have enough ER before investing in it.",
                "At R5, this weapon actually outperforms R1 Engulfing Lightning for DPS Shenhe, but it can make your ER requirements hard to meet. For on-field DPS Shenhe, the ER requirements are less of an issue.",
            ],
            [
                "LS",
                "Lithic Spear",
                "Good for on/off-field DPS, situational for support",
                "This weapon is decent when the team has at least 1 other Liyue character alongside Shenhe. This can be a viable option for Ganyu teams, but the typical Ayaka + Kokomi + Shenhe + Kazuha team contains no other Liyue characters, so consider your options carefully.",
                "The extra CRIT Rate is more useful for DPS Shenhe.",
            ],
            [
                "C",
                "The Catch",
                "Great for off-field DPS, situational for support",
                "While Shenhe doesn't rely much on her Elemental Burst damage as a support, the ER substat is much appreciated. The downside is how popular The Catch is with other characters (since you can only have one of it) and the annoyance of refining it.",
                "For off-field DPS Shenhe, this is a nice weapon as it helps with her ER needs and increases her Elemental Burst damage nicely. The downsides still apply, unfortunately.",
            ],
            [
                "PS",
                "Prototype Starglitter",
                "Good for on-field DPS, situational for off-field DPS, mediocre for support",
                "This is a decent fallback option that has good ER and doesn't require much effort to get. For off-field DPS Shenhe, CRIT options are more useful, but at least it still provides ER if you have nothing else to work with. For on-field DPS, the passive will actually be useful, and the ER will be helpful to have.",
            ],
            [
                "SoH",
                "Staff of Homa",
                "Great for on-field DPS, good for off-field DPS, mediocre for support",
                "This has been a go-to weapon for all DPS units and Shenhe is no exception. This weapon is simply good for Shenhe, though it is also desirable for all DPS polearm characters.",
                "For support Shenhe, the secondary CRIT DMG is unfortunately not that useful, so this weapon would not be recommended.",
            ],
            [
                "BP",
                "Blackcliff Pole",
                "Decent for off-field DPS, mediocre for support",
                "The CRIT DMG substat makes this viable for off-field DPS and this weapon is available through Paimon's Bargains. The ATK% passive can be usable for support Shenhe but combined with the complete lack of ER and energy related utility, it is not a recommended choice.",
            ],
            [
                "PJWS",
                "Primordial Jade Winged-Spear",
                "Decent for on-field DPS, mediocre/bad for off-field DPS and support",
                "For on-field DPS Shenhe, you will be using attacks and can stack the passive, and has a very useful CRIT Rate substat. In a Freeze comp, especially with Blizzard Strayer, you can hit almost 100% CRIT Rate, making it easy to reach an ideal CRIT ratio. For off-field and support Shenhe, you will not be able to use the passive at all, and the CRIT substat will not be helpful for support Shenhe, making almost all other options better.",
            ],
            [
                "DM",
                "Deathmatch",
                "Decent for on-field DPS, mediocre for off-field DPS, bad for support",
                "This weapon offers a high CRIT Rate and it's easy to hit almost 100% CRIT Rate in a Freeze team especially with Blizzard Strayer. The only drawback is the comparatively low ATK, which you will notice when adding Icy Quills into the equation. It can work for DPS Shenhe since Icy Quills being applied by other characters will occupy a smaller proportion of your damage.",
            ],
            [
                "WT",
                "White Tassel",
                "Mediocre for on-field DPS, terrible for off-field DPS and support",
                "If all else fails, you could make this work for on-field DPS Shenhe since the 24% Normal Attack DMG will actually apply, and the CRIT Rate doesn't hurt to have. However, the very low base ATK and lack of useful stats or ER make this a very bad option for any other Shenhe build.",
            ],
        ],
        characters: [
            [
                "Cryo (Freeze, Melt, Mono Cryo)",
                "",
                [
                    "Ayaka",
                    "Kamisato Ayaka",
                    "Cryo Main DPS",
                    "Both Ayaka and Shenhe scale rapidly with increased investment in Ayaka, as her damage is concentrated on her Elemental Burst damage window, which Shenhe can latch onto.",
                    "Icy Quill damage benefits incredibly well from Ayaka since she prioritizes high Cryo DMG% and CRIT, and because of Ayaka's natural ability to deal Cryo damage very quickly. As such, teams will have no problem fully using allocated Icy Quills, even twice per rotation (e.g. with C1 Shenhe).",
                    "Ayaka's Elemental Burst window is very friendly to Shenhe's held Elemental Skill, allowing fast use of additional Icy Quills for more front-loaded damage when needed.",
                    "Scales extremely well with Mistsplitter Reforged.",
                    "Shenhe provides key buffs to Ayaka's weaker matchups, namely bosses and other unfreezeable enemies.",
                    "Ayaka's C6 provides an extreme damage bonus for high synergy with Icy Quills.",
                    "Shenhe's C6 works very well with Ayaka's ability to deal Cryo damage very quickly with just attacks.",
                ],
                [
                    "Ganyu",
                    "Ganyu",
                    "Cryo Main DPS",
                    "Ganyu synergizes with Shenhe in a variety of playstyles, including Freeze, Melt, and Mono Cryo.",
                    "They can be difficult to pilot together due to Ganyu's Charged Attack playstyle and lack of protection without specific characters. The pair can run shieldless teams, and typically Melt Ganyu is played with C6 Ganyu.",
                    "Ganyu consumes Icy Quills easily with her Elemental Burst and also often builds Cryo DMG% and CRIT which are good for Icy Quills.",
                ],
                [
                    "Aloy",
                    "Aloy",
                    "Cryo Main DPS",
                    "Shenhe works well for quick-swap teams and amazingly for main DPS Aloy. She can use all of Shenhe's talents to varying degrees.",
                    "Aloy buffs Shenhe's ATK (which will apply as Shenhe's Elemental Skill does not snapshot), allowing for Icy Quills to hit even harder.",
                    "Easier time managing energy due to Aloy's low cooldown, high particle generation, and 40 energy Elemental Burst.",
                    "Aloy cannot use all of Shenhe's Icy Quills if you don't focus on triggering the bomblets, which lowers your damage ceiling. Consider building off-field DPS Shenhe in that case.",
                ],
                [
                    "Diona",
                    "Diona",
                    "Cryo Support / Shielder",
                    "Cryo shielder and healder who can also consume Icy Quills.",
                    "Diona's Elemental Skill consumes 5 Icy Quills when held, so a Diona built for damage can nuke with her held Elemental Skill. C1 Shenhe and a Sacrificial Bow on Diona can deal very high single-target damage in a short window.",
                    "Diona is an amazing battery, which helps Shenhe a lot.",
                    "Team options are generally limited to Mono Cryo or specific Melt teams.",
                    "Diona's C6 EM bonus is useful in a few teams such as Mono Cryo with Kazuha.",
                ],
                [
                    "Chongyun",
                    "Chongyun",
                    "Cryo Support",
                    "Chongyun's Cryo infusion provides many new team options that Shenhe can buff or be the star of; notably, it enables on-field Cryo DPS Shenhe.",
                    "Chongyun can easily consume 5 Icy Quills.",
                    "Chongyun's C2 is a rare and useful bonus for Shenhe.",
                    "Shenhe's C1 is difficult for Chongyun to use properly if not on-field.",
                    "Most team options are better suited for casual play rather than speedrunning or getting 36 stars in the Spiral Abyss.",
                    "Shenhe's C6 unlocks the Cryo infusion's maximum potential, but that is out of reach of most players.",
                ],
                [
                    "Kaeya",
                    "Kaeya",
                    "Cryo Main DPS",
                    "Easy usage of Icy Quills thanks to his Elemental Burst.",
                    "Given for free and functional at C0.",
                    "Has increased energy generation in Freeze teams.",
                    "Kaeya can fit into many team options (Cryo Infusion, Melt, Freeze, and Physical).",
                    "Great potential for C1 Shenhe to shine.",
                    "Few teams are actually very competitive, limited to Mono Cryo and Freeze variants.",
                    "Constellations aren't crucial but help a lot for a character that is only obtainable from the standard banner, especially C6.",
                ],
                [
                    "Rosaria",
                    "Rosaria",
                    "Cryo Sub-DPS",
                    "Consumes all Icy Quills steadily.",
                    "Slower Elemental Burst pulses open powerful Reverse Melt options as each Rosaria tick can Melt, further amplifying Icy Quill damage.",
                    "Can help battery Shenhe, though not as well as Kaeya.",
                    "C1 Shenhe is underwhelming unless Rosaria is on-field.",
                    "Rosaria and Shenhe generally fight for a slot in Freeze teams instead of playing together.",
                ],
                [
                    "Layla",
                    "Layla",
                    "Cryo Support / Shielder",
                    "Cryo shielder who can also consume Icy Quills.",
                    "Solid battery potential, though do note that it is reliant on the shield staying up.",
                    "Team options are generally limited to Mono Cryo or specific Melt teams.",
                    "Their vastly different scalings make it hard to help both at the same time.",
                ],
            ],
            [
                "Physical",
                "Note that Shenhe should be built as a Cryo DPS and not an Icy Quill support as most of these units do not use Icy Quills enough or cannot apply it at all. These teams will usually have energy problems and require one or two batteries. Finally, non-Cryo Physical units have little to no use for Shenhe's constellations beyond C1.",
                [
                    "Eula",
                    "Eula",
                    "Physical Main DPS",
                    "Utilizes all of Shenhe's talents, even the Icy Quills.",
                    "Eula benefits from many of Shenhe's buffs, including the Physical RES shred and Elemental Burst DMG bonus.",
                    "When finishing Eula's part of the rotation, you can switch to Shenhe and cast her Elemental Skill before Eula's Elemental Burst hits, ensuring the 15% damage boost is active. This requires some practice.",
                    "Claymore staggering can end up pushing enemies out of Shenhe's Elemental Burst field.",
                    "Has synergy with Shenhe's C1 + C2.",
                ],
                [
                    "Razor",
                    "Razor",
                    "Physical Main DPS",
                    "Consistent Elemental application from both, ensuring easy Superconduct uptime.",
                    "Flexible team options as the basic needs for a physical team are covered.",
                    "Razor benefits from both the press and hold variants of Shenhe's Elemental Skill (though pressing it is preferred).",
                    "C1 Shenhe is partially beneficial for buffing both parts of Razor's kit via A4.",
                    "Razor may prefer Aggravate and Hyperbloom teams these days instead.",
                ],
                [
                    "Fischl",
                    "Fischl",
                    "Physical Main DPS",
                    "Very consistent Superconduct, especially at C6.",
                    "Flexible team options.",
                    "Limited results compared to Electro builds.",
                    "A shielder is recommended to protect Fischl.",
                    "Can be annoying to operate due to Fischl being quite frail and needing to keep enemies in Shenhe's Elemental Burst's field for optimal results.",
                ],
                [
                    "Xinyan",
                    "Xinyan",
                    "Physical Main DPS",
                    "Shenhe supports both Physical Nuke and DPS Xinyan.",
                    "Melt is reliant on maintaining Xinyan's shield, which is weak due to Xinyan not building DEF as a DPS.",
                    "Xinyan benefits from both A4 buffs.",
                    "Since you need an Electro unit for Superconduct, you risk Overloading which will consume your Elemental application and potentially knock enemies away from Xinyan and Shenhe's Elemental Burst's field.",
                ],
                [
                    "Mika",
                    "Mika",
                    "Physical Support",
                    "Specialist Physical support and also a Cryo unit. In theory, he is very helpful for both main-DPS Shenhe and teams where they both support a core Physical unit.",
                    "Playtesting is still needed to verify his strength, so no more information is available here yet.",
                ],
                [
                    "Qiqi",
                    "Qiqi",
                    "Physical Main DPS",
                    "If running the Ocean-Hued Clam artifact set, the burst of damage benefits from Shenhe's Elemental Burst.",
                    "Team-wide ATK buffs benefit both characters.",
                    "Terrible particle generation, requiring one or even two batteries (Qiqi's Elemental Skill generates no particles).",
                    "Difficult to make good use of Icy Quills, as Qiqi typically just stacks ATK like Shenhe, so the Icy Quill damage gains no bonus from Cryo DMG% or CRIT.",
                ],
            ],
            [
                "Hydro Applicants",
                "These are lumped together as they generally are meant to synergize more with the core unit and their synergy with Shenhe herself warrants less discussion. Generally, both will help the core unit and not each other. Ultimately, you want consistent Freeze, so the core unit needs to provide enough Cryo application.",
                [
                    "Kokomi",
                    "Kokomi",
                    "Hydro Applicant (Joint Support)",
                    "Kokomi's Elemental Skill is always cast right next to her, making it easy to control AoE Freeze zones.",
                    "With Anemo / grouping characters, it is easy to keep enemies within range of the Freeze zone or move them into it.",
                    "This is niche, but Kokomi + Shenhe + Electro can boost the Ocean-Hued Clam damage, as it is Physical. This may apply Electro-Charged instead of Superconduct, but that is not as harmful as accidentally applying Overload.",
                ],
                [
                    "Yelan",
                    "Yelan",
                    "Hydro Applicant (Support, DPS Shenhe)",
                    "Yelan is somewhat better for when Shenhe is using her attacks to trigger the Hydro coordinated attacks, since her attack speed is slower than most polearm characters.",
                ],
                [
                    "Mona",
                    "Mona",
                    "Hydro Applicant + Buffer (Support, DPS Shenhe)",
                    "Mona offers good synergy with DPS Shenhe through maintaining the Omen buff.",
                    "Mona is not as good as Kokomi for running both as joint supports for another core unit.",
                ],
                [
                    "Xingqiu",
                    "Xingqiu",
                    "Hydro Applicant (Support, DPS Shenhe)",
                    "Yelan may perform better as Shenhe's Normal Attacks are slower than most polearm characters, resulting in a minor loss to Xingqiu's Elemental Burst's fire rate.",
                ],
            ],
            [
                "Ayato/Tartaglia",
                "Both are Normal Attack-centric Hydro DPS units. Unsurprisingly, both are decent with Shenhe in Freeze teams, and an additional Cryo unit is expected for consistent freezing and Cryo resonance.",
                [
                    "Ayato",
                    "Kamisato Ayato",
                    "Hydro Main DPS",
                    "Ayato is easier to pilot than Tartaglia here.",
                    "Reasonable synergy, but Shenhe is generally less relevant than other off-field Cryo units like Ganyu.",
                ],
                [
                    "Tartaglia",
                    "Tartaglia",
                    "Hydro Main DPS",
                    "Tartaglia requires fairly precisely planned rotations, making him harder to play than Ayato (albeit this has no implications for their strengths)",
                    "Reasonable synergy, but Shenhe is generally less relevant than other off-field Cryo units like Ganyu.",
                ],
            ],
            [
                "Anemo Groupers",
                "Assuming they are there to support Shenhe directly, their grouping is good for keeping units within Shenhe's Elemental Burst's field and the buff from Viridescent Venerer is good. Also, because they can infuse Cryo with their Anemo talents, they are able to consume Icy Quills despite not being Cryo characters.",
                [
                    "Kazuha",
                    "Kaedehara Kazuha",
                    "Anemo Grouper",
                    "Kazuha is the generalist option, offering Cryo DMG buffing that is easier to set up and making Shenhe's Icy Quills stronger.",
                    "Direct synergy through his suction pulling enemies into him, making him the easiest grouper for keeping enemies in Shenhe's Elemental Burst's field.",
                    "His Plunging Attacks can Shatter Frozen enemies which can cause issues depending on your Hydro applicant.",
                ],
                [
                    "Venti",
                    "Venti",
                    "Anemo Grouper",
                    "Venti is a strong grouper and battery.",
                    "Venti's Elemental Burst makes it unreliable to hit enemies with Shenhe's melee attacks and aims his suction in front of him with can be unpredictable and may require repositioning to avoid grouping enemies in an undesirable location.",
                ],
                [
                    "Sucrose",
                    "Sucrose",
                    "Anemo Grouper",
                    "Sucrose is low investment and can carry Thrilling Tales of Dragon Slayers to allow Cryo DPS Shenhe to have high Icy Quill damage on top of her Cryo DPS build.",
                    "The EM buff is not useful for Freeze teams and her C6 buff is awkward to set up.",
                ],
                [
                    "Traveler",
                    "Anemo Traveler",
                    "Anemo Grouper",
                    "Everyone has the Anemo Traveler, but their Elemental Burst picks up enemies and moves them away from Shenhe's Elemental Burst's field and drops them randomly.",
                    "They should only be used if no other options are available.",
                ],
            ],
            [
                "Pyro (Melt, General)",
                "",
                [
                    "Xiangling",
                    "Xiangling",
                    "Pyro Sub-DPS, Melt Enabler",
                    "Solid synergy in Melt teams, with either Xiangling applying Melt with her Pyronado or providing Pyro application for Shenhe and another Cryo teammate to Melt.",
                    "Both characters are good in quick-swap teams for flexibility and energy generation.",
                    "Xiangling also appreciates Shenhe's common build with Favonius Lance, helping generate energy for Pyronado.",
                ],
                [
                    "Bennett",
                    "Bennett",
                    "Pyro Buffer, Situational Melt Enabler",
                    "Shenhe needs to be on-field for Bennett's Elemental Burst's buff.",
                    "Outside of dedicated Shenhe DPS teams, where she takes advantage of both ATK stacking and a DPS build, Bennett is better off buffing the core unit rather than giving Shenhe the buff and Shenhe giving only 80% of it via a limited number of Icy Quills.",
                    'In combination with Jean ("Sunfire"), the consistent Pyro Swirl allows Shenhe to consistently Melt.',
                    "Bennett works very well for Mono Cryo teams as a dedicated healer and second support.",
                ],
            ],
        ],
    };
};
